# Generated by Django 3.0.3 on 2020-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
